#Ask the user for at least ten questions
#Read in each answer and store it in a variable
#Print out the result

print("Welcome to Mad Libs!")
print("Give me a name: ")
name=input()
print("Give me a verb: ")
verb =input()
print("One day",name,verb,"a Mad Lib for class!")
print("give me an adjective")
adjective=input()
print("in the morning",name,adjective,"by a mad lip")
print("give me a number")
number=input()
print("yestarday",name,adjective,number,"with a mad lip" )
print( "give me a place")
place=input()
print(" monday",name,verb,place,"with a madlip")
print("give me a date")
date=input()
print("on",date,place,verb,"with madlip")
print("give me a noun")
noun=input()
print("on friday" ,name,verb,noun,"with a madlip")
print("give me time")
time=input()
print("on friday",__name__,verb,noun,time,"with a madlip")
print("give me examples")
examples=input()
print("tomorrow",name,verb,examples,"witha madlip")
print(" give me  an app")
app=input()
print("on",date,name,verb,app,"with madlip")

